# German
# Adjusted and adapted to typical system namings with neutral wording. Error correction complete.

[addon]
appDesc = '''Videos aus dem Internet herunterladen.'''
restore_purchase_button = '''Kauf wiederherstellen'''
get_premium_button = '''Premium holen'''
back = '''Zurück'''
waiting_for_media = '''Auf Medien warten…'''
nomedia_title = '''Die gesuchten Medien konnten nicht gefunden werden?'''
nomedia_description = '''Video starten (mögliche Werbung überspringen) um die Medienerkennung zu verbessern. Oder fehlende Medien melden.'''
nomedia_reload_button = '''Erkennung erzwingen'''
nomedia_reload_button_tooltip = '''Seitenneustart erzwingen (Cookies löschen)'''
show_nomedia_button = '''Kein Video?'''
show_nomedia_button_tooltip = '''Hier klicken wenn kein Video gefunden wurde'''
setting_button_tooltip = '''Einstellungen'''
history_button_tooltip = '''Downloadverlauf anzeigen'''
show_all_history_button = '''alle anzeigen'''
complete_title = '''Abgeschlossen'''
hide_complete_button = '''verstecken'''
translate_button_tooltip = '''Mithelfen, VDH zu übersetzen'''
open_source_tab_button_tooltip = '''Tab mit Medienquelle öffnen'''
retry_download_button_tooltip = '''Download erneut versuchen'''
delete_file_button_tooltip = '''Datei löschen'''
download_directory_button_tooltip = '''Download-Ordner anzeigen'''
clear_downloaded_tooltip = '''Vollständige Downloads entfernen'''
show_in_popup_button_tooltip = '''Als PopUp anzeigen'''
show_in_sidebar_button_tooltip = '''In der Seitenleiste anzeigen'''
video_not_playing_button_tooltip = '''Video wird nicht abgespielt?'''
play = '''Wiedergabe'''
warn_drm_tooltip = '''DRM gefunden'''
version_title = '''Version'''
account_title = '''Bentzerkonto'''
one_hundred_downloads_title = '''Du hast 100 Videos heruntergeladen!'''
leave_review_description = '''Wir hoffen, dass dir Video DownloadHelper gefällt. :) Würdest du eine positive Bewertung auf der Erweiterungsseite hinterlassen?'''
leave_review_button = '''Bewertung abgeben'''
account_status = '''Status'''
account_status_premium = '''Premium ($1)'''
free_account = '''Gratis'''
copy_to_clipboard = '''Informationen in die Zwischenablage kopieren'''
my_account_button = '''Mein Benutzerkonto'''
download_title = '''Downloads'''
show_notification = '''Benachrichtigung anzeigen sobald ein Download abgeschlossen ist'''
max_parallel_downloads = '''Max. parallel laufende Downloads'''
change_download_directory = '''Downloadverlauf ändern'''
saveas_detected_warning = '''Dieser Browser zeigt den 'Speichern unter' Dialog, sobald ein Download abgeschlossen ist. Es wird empfohlen, diese Option in den Browsereinstellungen zu deaktivieren.'''
change_saveas_setting = '''Option ändern'''
private_browsing_title = '''Privates Browsen'''
private_browsing_warning = '''Video DownloadHelper ist für Privates / Verstecktes Browsen nicht aktiviert. Diese Option muss manuell aktiviert werden falls sie genutzt werden soll.'''
private_browsing_notifications = '''Benachrichtigung für private Downloads anzeigen'''
private_browsing_button = '''Option für Privates Browsen ändern'''
prefer_original_audio = '''Originales Audio bevorzugen'''
prefer_hls = '''HLS bevorzugen'''
settings_history_title = '''Verlauf'''
transient_history_description = '''Abgeschlossene Downloads in der Leiste anzeigen'''
history_limit = '''Downloadverlauf nach X Tagen leeren'''
appearance_title = '''Erscheinungsbild'''
theme_title = '''Design'''
theme_light = '''Hell'''
theme_dark = '''Dunkel'''
theme_system = '''System'''
popup_size_title = '''Fenstergröße'''
popup_size_small = '''Klein'''
popup_size_medium = '''Mittel'''
popup_size_big = '''Groß'''
panel_position_title = '''Position'''
use_popup = '''Als PopUp anzeigen'''
use_sidebar = '''In der Seitenleiste anzeigen'''
behavior_title = '''Verhalten'''
show_in_context_menu = '''Kontextmenü auf Webseiten aktivieren'''
restart_addon = '''Erweiterung neu laden'''
reset_settings = '''Einstellungen zurücksetzen'''
prefer_highest_quality = '''Höchste verfügbare Qualität statt 1080p auswählen (langsamerer Download, höhere Qualität)'''
preview_mode_title = '''Medienvorschau'''
preview_mode_none = '''Deaktiviert'''
preview_mode_video = '''Kurze Videovorschau'''
preview_mode_image = '''Bild'''
history_title = '''Downloadverlauf'''
history_warning = '''Der Downloadverlauf wird aktuell nicht angelegt. Soll Video DownloadHelper den Downloadverlauf speichern?'''
history_warning_2 = '''Der Downloadverlauf wird nur lokal auf dem System gespeichert. Privatsphäre geht vor.'''
enable_history = '''Verlauf aktivieren'''
clear_history = '''Verlauf leeren'''
disable_history = '''Verlauf nicht speichern'''
no_downloads_yet = '''Keine Einträge'''
download_failed = '''Download fehlgeschlagen'''
download_failed_description = '''Die gewünschten Medien konnte nicht heruntergeladen werden. Um möglichst viele Webseiten unterstützen zu können, hilft es, einen (anonymen!) Fehlerbericht einzureichen.'''
download_interrupted = '''Download unterbrochen'''
download_interrupted_description = '''Die Datei konnte heruntergeladen werden, es gab allerdings Netzwerkprobleme, sodass die Datei möglicherweise kürzer ist als erwartet. Um möglichst viele Webseiten unterstützen zu können, hilft es, einen (anonymen!) Fehlerbericht einzureichen.'''
download_with_drm_failed_description = '''Etwas ist schief gelaufen. Vermutlich ist das Video DRM-geschützt. DRM-geschützte Videos werden nicht unterstützt.'''
no_youtube = '''Downloads von YouTube werden nicht unterstützt.'''
no_youtube_description = '''Leider erlaubt der Chrome Web Store keine Erweiterungen für das Herunterladen von YouTube-Videos, so dass diese Funktion in der Chrome-Version der Erweiterung nicht aktiv ist.'''
premium_required = '''Premium-Status benötigt'''
premium_yt_required_description = '''Ohne Premium-Status kann ein YouTube-Download erst 2 Stunden nach dem vorherigen Download durchgeführt werden.'''
premium_required_description = '''Ohne Premium-Status kann ein HLS- oder MPD-Download erst 2 Stunden nach dem vorherigen Download durchgeführt werden.'''
youtube_too_many_downloads = '''YouTube scheint gesperrt zu sein'''
youtube_too_many_downloads_description = '''YouTube begrenzt zeitweise die Anzahl der Videos, die angefordert werden können. Bitte später erneut versuchen.'''
stop = '''Anhalten'''
cancel = '''Abbrechen'''
copy_url = '''URL kopieren'''
always_copy_url = '''URL immer kopieren'''
download_button = '''Herunterladen'''
download_as_button_and_menu = '''Herunterladen als…'''
rename_short = '''Umbenennen'''
always_download_as_menu = '''Immer herunterladen als…'''
download_audio_button = '''Audio'''
download_audio_and_video_menu = '''Audio & Video herunterladen'''
download_audio_only_menu = '''Audio herunterladen'''
audio_only_for_this_website = '''Für diese Webseite immer nur Audio herunterladen'''
details = '''Details'''
more_settings = '''Weitere Einstellungen'''
report = '''Fehlerbericht '''
reporting = '''Fehlerbericht wird eingereicht…'''
reported = '''Fehlerbericht erfolgreich eingereicht. Vielen Dank!'''
not_playing_title = '''Das Video wird nicht abgespielt?'''
not_playing_broken_title = '''Defektes Audio oder Video?'''
not_playing_broken_description = '''Fehlgeschlagene Medien melden. Die Medien werden analysiert um zu prüfen, was schief gelaufen ist. Die URL wird anonym eingereicht!'''
not_playing_broken_solution_title = '''Modernen Videoplayer verwenden'''
not_playing_broken_solution_windows_1 = '''VLC wird empfohlen:'''
not_playing_broken_solution_mac_1 = '''IINA wird empfohlen:'''
not_playing_broken_solution_2 = '''modern, sicher und Open Source.'''
not_playing_default_player = '''Der Videoplayer muss als Standardvideoplayer im System festgelegt sein.'''
not_playing_default_player_solution_windows = '''Unter Windows' "Einstellungen", "Apps", "Standard-Apps" den Videoplayer festlegen.'''
not_playing_default_player_solution_mac = '''Download-Verzeichnis öffnen und mit der rechten Maustaste auf die Videodatei klicken. Auf 'Informationen abrufen' klicken. Im Abschnitt 'Öffnen mit' die Option 'IINA' auswählen. Auf die Schaltfläche 'Alle ändern' klicken.'''

[web]
back = '''Zurück'''
header_help = '''Hilfe'''
header_community = '''Community'''
activate_title = '''Aktivierung'''
activate_pending = '''Ausstehend…'''
activate_success = '''Erfolgreich'''
activate_error = '''Fehler'''
activate_no_addon_found = '''Keine Erweiterung gefunden. Ist die Erweiterung installiert?'''
activate_no_method_found = '''Keine Methode gefunden.'''
activate_help_me = '''Hilf mir'''
issue_title = '''Wiederherstellung des Kaufs'''
issue_submit = '''Einreichen'''
issue_thank_you = '''Vielen Dank'''
issue_enter_email = '''Um den Kauf wiederherzustellen, bitte die E-Mail-Adresse eingeben, die beim Kauf der Lizenz verwendet wurde:'''
issue_email_sent = '''Ein Link zum Aktivieren des Produkts wurde per E-Mail verschickt.'''
issue_or_digit = '''Oder den 6-stelligen Code eingeben, der verschickt wurde:'''
issue_just_digit = '''Bitte den 6-stelligen Code eingeben, der verschickt wurde:'''
issue_i_have_a_code = '''(Bei vorhandenem Code, hier klicken)'''
issue_i_have_a_key = '''(Bei vorhandenem Lizenzschlüssel, hier klicken)'''
issue_key = '''Video DownloadHelper Lizenzschlüssel eingeben:'''
landing_text1 = '''Beliebige Videos von beliebigen Websites herunterladen. Schnell und einfach!'''
landing_text2 = '''Mehr als 1000 unterstützte Webseiten'''
landing_text3 = '''Von 7 Millionen Nutzern genutzt'''
landing_text4 = '''4.5 Sterne im Erweiterungsstore'''
landing_install_for_google = '''Für Chrome installieren'''
landing_install_for_mozilla = '''Für Firefox installieren'''
landing_install_for_microsoft = '''Für Edge installieren'''
landing_feature1_title = '''HD-Download mit maximaler Geschwindigkeit'''
landing_feature1_description = '''Hochauflösende Videos mit maximaler Geschwindigkeit dank der schnellsten Download-Engine auf dem Markt herunterladen.'''
landing_feature2_title = '''Video archivieren'''
landing_feature2_description = '''Lieblingsvideos archivieren und sicher gehen, dass die Sammlung vollständig und immer verfügbar ist.'''
landing_feature3_title = '''Live-Stream-Unterstützung'''
landing_feature3_description = '''Live-Streams offline und ohne die typischen Live-Einschränkungen anschauen.'''
landing_feature4_title = '''Audio herunterladen'''
landing_feature4_description = '''Audio aus Videos extrahieren und in MP3-Dateien konvertieren.'''
premium_hero1 = '''Einmal bezahlen, für immer nutzen'''
premium_hero2 = '''Lizenz auf Lebenszeit für Video DownloadHelper holen'''
premium_hero3 = '''Ohne Einschränkungen beliebig oft Videos herunterladen.'''
welcome_text = '''Nie wieder ein Video verpassen!'''
welcome_pin_message = '''Erweiterung als Symbol in der Symbolleiste anheften:'''
